name = "InterpolatedPDFs"
uuid = "dd871ef8-c280-11e9-0edd-21d59c0cc143"
authors = ["m-wells <maw461@psu.edu>"]
version = "0.1.1"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
NumericalIntegration = "e7bfaba1-d571-5449-8927-abc22e82249b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Distributions = "0.23, 0.24, 0.25"
Interpolations = "0.12, 0.13, 0.14"
NumericalIntegration = "0.2, 0.3"
StatsBase = "0.33, 0.34"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
